### PR TITLE
Python3 compatibility (draft)

### PR DESCRIPTION
**Pull request by GabLeRoux**
Relates to #12

More precisely https://github.com/skleinei/alfred-confluence/issues/12#issuecomment-1104377598

Current pr is in preparation and will be valid only when upstream issue https://github.com/deanishe/alfred-workflow/issues/97 gets solved.

### CODE REVIEW

**Comment by mcouthon** [comment]
There's a bunch of Python 3 incompatible code in web.py as well.

**Comment by GabLeRoux** [comment]
> There's a bunch of Python 3 incompatible code in web.py as well.

https://github.com/skleinei/alfred-confluence/blob/master/src/lib/workflow/web.py

This file is from the following library:  
https://github.com/deanishe/alfred-workflow#readme

Hence it would be preferable to use a fix from the library itself. That is why I did not attempt to fix scripts inside `src/lib/workflow` folder ;)

**Comment by mcouthon** [comment]
@GabLeRoux check out #15 . I've tested it and it's working for me (didn't verify update workflow, tbh).
If you think it's good enough, you can use it :)

**Comment by skleinei** [comment]
@mcouthon, @jodosha, and everyone – as mentioned in https://github.com/skleinei/alfred-confluence/pull/15:

----

Many thanks for your efforts to fix this. I've rewritten _Confluence Quicksearch for Alfred_ to work with Python 3 (and hence macOS 12.3). The new version also requires Alfred 5, because the new version uses Alfreds' new workflow configuration. Also it's not using the Workflow library. Read more: https://github.com/skleinei/alfred-confluence/discussions/16

Let me know, if/how the new version works for you.

As a result of this I will close this PR.

**Pull request closed without merging**
