### PR TITLE
Update workflow to Python 3 & MacOS 12.3

### PR DESCRIPTION
**Pull request by mcouthon**

### CODE REVIEW

**Comment by jodosha** [comment]
@skleinei Thanks for this extremely useful, time-saving workflow. I miss it now that is broken on my computer 😿 .
Would you please consider to merge this PR and release an update? 🙏 

Thanks.

**Comment by mcouthon** [comment]
@jodosha check out the [release](https://github.com/mcouthon/alfred-confluence/releases/tag/1.1.0) I added to my fork. Obviously I'm trying to overtake the original maintainer, but it works for me for now.

**Comment by jodosha** [comment]
@mcouthon It works. Thank you very much! 🐈

**Comment by skleinei** [comment]
@mcouthon, @jodosha, and everyone – many thanks for your efforts to fix this. I've rewritten _Confluence Quicksearch for Alfred_ to work with Python 3 (and hence macOS 12.3). The new version also requires Alfred 5, because the new version uses Alfreds' new workflow configuration. Also it's not using the Workflow library. Read more: https://github.com/skleinei/alfred-confluence/discussions/16

Let me know, if/how the new version works for you.

As a result of this I will close this PR.

**Pull request closed without merging**
